name: Update folderData.json

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 运行脚本生成 folderData.json
      - name: Generate folderData.json
        run: |
          python generate_folder_data.py

      # 4. 提交更新（如果有变更）
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add folderData.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update folderData.json"
            git push
          fi
